default: &default
   adapter: postgresql
   encoding: unicode  
   pool: 5
   timeout: 5000
   username: ivan
   password: 

development:
  <<: *default
  database: redress_dev

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  <<: *default
  database: redress